[project]
name = "bot"
description = "Bot aldemarromel :D"
readme = "README.md"
version = "0.0.1"
dependencies = [
	"RPi.GPIO >= 0.7.1",
	"mediapipe",
	"protobuf >= 3.20.0",
	"pynmea2",
	"pyserial"
]
requires-python = ">= 3.1"

[project.scripts]
